import type { AlertRecord, Explanation, PeerComparison, PortfolioRiskRow, PriorityRecord, ProjectDetail, ProjectListItem, ScenarioRecommendations, TrajectoryPoint, WhatIfConfig } from "../types";

export const project: ProjectListItem = { canonical_project_id: "P-001", project_name: "National Corridor Project", sector: "Road Transport", state: "Maharashtra", latest_snapshot_month: "2026-01", latest_risk_score: 0.61 };
export const riskRow: PortfolioRiskRow = { ...project, risk_level: "CRITICAL", latest_quality_score: 91, risk_change: 0.12 };
export const trajectory: TrajectoryPoint[] = [
  { snapshot_month: "2025-12", predicted_delay_probability_3m: 0.49, risk_level: "CRITICAL", data_quality_score: 90 },
  { snapshot_month: "2026-01", predicted_delay_probability_3m: 0.61, risk_level: "CRITICAL", data_quality_score: 91 },
];
export const explanation: Explanation = { canonical_project_id: "P-001", snapshot_month: "2026-01", delay_probability_3m: 0.61, risk_level: "CRITICAL", top_risk_drivers: [{ feature: "schedule_pressure", label: "Schedule pressure", observed_value: 1.8 }], top_protective_drivers: [{ feature: "physical_progress_pct", label: "Current physical progress", observed_value: 82 }], explanation: "Schedule pressure increases risk while progress reduces it. These are predictive associations, not causal effects." };
export const detail: ProjectDetail = { canonical_project_id: "P-001", project_metadata: { project_name: project.project_name, sector: project.sector, state: project.state, ministry_department: "Ministry of Road Transport", agency: "NHAI", reporting_regime: "PAIMANA", identity_source: "PAIMANA_ID", identity_confidence: "HIGH" }, latest_snapshot: { snapshot_month: "2026-01", current_target_doc: "2027-03-01", current_forecast_cost_cr: 1200, cumulative_expenditure_cr: 700, physical_progress_pct: 82, data_quality_score: 91, quality_flags: "" }, historical_snapshots: [{ snapshot_month: "2025-12", current_target_doc: "2027-03-01", current_forecast_cost_cr: 1200, cumulative_expenditure_cr: 650, physical_progress_pct: 78, data_quality_score: 90, quality_flags: "" }, { snapshot_month: "2026-01", current_target_doc: "2027-03-01", current_forecast_cost_cr: 1200, cumulative_expenditure_cr: 700, physical_progress_pct: 82, data_quality_score: 91, quality_flags: "" }], current_delay_probability_3m: 0.61, current_delay_probability_6m: 0.74, delay_6m_model_status: "GREEN", risk_level: "CRITICAL", explanation, data_quality_score: 91 };
export const peers: PeerComparison = { canonical_project_id: "P-001", available: true, peer_group_definition: { sector: "Road Transport" }, peer_count: 12, minimum_peer_size: 5, project_physical_progress_pct: 82, peer_median_physical_progress_pct: 65, peer_relative_progress_difference_pct: 17, project_expenditure_ratio_pct: 58, peer_median_expenditure_ratio_pct: 52, project_delay_risk: .61, peer_median_delay_risk: .35, risk_percentile: 88, progress_percentile: 75 };
export const alerts: AlertRecord[] = [{ alert_id: "P-001:CRITICAL_RISK:2026-01", canonical_project_id: "P-001", project_name: project.project_name, alert_type: "CRITICAL_RISK", severity: "CRITICAL", priority_score: 88, intervention_priority_score: 94, intervention_priority_level: "CRITICAL", current_risk: .61, recent_risk_change: .12, data_reliability_score: 91, latest_snapshot_month: "2026-01", explanation: "Risk band is critical." }];
export const priority: PriorityRecord = { rank: 1, canonical_project_id: "P-001", project_name: project.project_name, sector: project.sector, ministry_department: "Ministry of Road Transport", state: project.state, delay_probability_3m: .61, delay_probability_6m: .74, risk_level: "CRITICAL", data_reliability_score: 91, intervention_priority_score: 94, intervention_priority_level: "CRITICAL", recommended_review_action: "IMMEDIATE_REVIEW", trajectory_status: "ACCELERATING", risk_change_1m: .12, risk_change_3m: .27, risk_velocity: .09, risk_acceleration: .05, history_observations: 4, top_priority_reasons: ["High 3-month delay risk", "Risk is accelerating"], key_reason: "High 3-month delay risk", score_components: { schedule_risk: 30, trajectory: 18, alerts: 15, peer: 9, exposure: 10, schedule_pressure: 12 } };
export const whatIfConfig: WhatIfConfig = { canonical_project_id: "P-001", controls: [{ feature: "progress_velocity_3m", label: "Expected physical progress velocity", minimum: -2, maximum: 8, current: 2, step: .1 }], disclaimer: "This scenario reflects model behavior under modified inputs and does not imply guaranteed causal impact." };
export const scenarios: ScenarioRecommendations = { canonical_project_id: "P-001", recommendations: [{ rank: 1, feature: "progress_velocity_3m", label: "Expected physical progress velocity", current_value: 2, scenario_value: 4, current_risk: .61, scenario_risk: .52, difference_percentage_points: -9, feasibility_score: 80, wording: "Under this model scenario, changing expected physical progress velocity from 2.00 to 4.00 changes estimated delay risk from 61.0% to 52.0%." }], disclaimer: whatIfConfig.disclaimer };
